title: Welcome to TyataEssence blog - a space where complexity meets clarity!
author: Rakesh Tyata
email: tyataessence@gmail.com
description: "This blog is about sharing ideas — it’s about creating a place where readers can slow down, think clearly, and discover meaningful perspectives in a fast-moving world."
baseurl: ""
url: "https://tyataessence.github.io"

# Add this instead:
remote_theme: mmistakes/minimal-mistakes@4.27.3

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache
  
paginate: 5
paginate_path: "/page:num/"
