title: Welcome to TyataEssence blog - a space where complexity meets clarity!
author: Rakesh Tyata
email: tyataessence@gmail.com
description: "This blog is about sharing ideas — it’s about creating a place where readers can slow down, think clearly, and discover meaningful perspectives in a fast-moving world."
baseurl: ""
url: "https://tyataessence.github.io"

# Sidebar settings
show_sidebar: true

sidebar:
  author:
    name: "Rakesh Tyata"
    bio: "Blogger | Developer | Thinker - Making complex ideas simple, from tech to personal insights and trending stories."
    image: "/assets/images/rakesh_headshot.jpg"  # place profile image here
    email: "tyataessence@gmail.com"
    address: "Seattle, WA, USA"
    links:
      View My Portfolio: "https://rtyata01.github.io/"
      View My Youtube: "https://youtube.com/tyataessence"
      View My Linkedin: "https://linkedin.com/in/rtyata"
  
  categories:
    - Personal
    - Technical
    - Trending

# Add this instead:
remote_theme: mmistakes/minimal-mistakes@4.27.3

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Use custom homepage layout for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"

